<?php

require_once 'fcollab_project.node.inc';

/**
 * Implementation of hook_menu()
 */
function fcollab_project_menu(){
	$items['project'] = array(
		'title' => 'Project',
		'page callback' => 'fcollab_project_list',
		'access arguments' => array('access content'),
		'type' => MENU_SUGGESTED_ITEM,
		'file' => 'fcollab_project.pages.inc',
	);
	return $items;
}

/**
 * Implementation of hook_node_info()
 */
function fcollab_project_node_info() {
  return array(
    'fcollab_project' => array(
      'name' => t('project'),
      'module' => 'fcollab_project',
      'description' => "Project for freelancer, this is posted by employer.",
      'body_label' => 'Brief description',
    ),
  );
}

/**
* Implementation of hook_perm().
*/
function fcollab_project_perm() {
  return array('create fcollab_project', 'edit own fcollab_project');
}

/**
* Implementation of hook_access().
*/
function fcollab_project_access($op, $node) {
  global $user;

  if ($op == 'create') {
    // Only users with permission to do so may create this node type.
    return user_access('create fcollab_project');
  }

  // Users who create a node may edit or delete it later, assuming they have the
  // necessary permissions.
  if ($op == 'update' || $op == 'delete') {
    if (user_access('edit own fcollab_project') && ($user->uid == $node->uid)) {
      return TRUE;
    }
  }
}

/**
* Implementation of hook_theme().
*/
function fcollab_project_theme() {
	return array(
		'fcollab_project_cost_info' => array(
			'arguments' => array('node'),
		),
		'fcollab_project_view_bid' => array(
			'arguments' => array('node'),
		),
	);
}

?>